---
- name: Make sure .vim directory exists
  file:
    path: "{{ ansible_env.HOME }}/.vim/autoload"
    state: directory
    mode: 0755
  become: yes
  become_user: "{{ user }}"

- name: Make sure .vim colors directory exists
  file:
    path: "{{ ansible_env.HOME }}/.vim/colors"
    state: directory
    mode: 0755
  become: yes
  become_user: "{{ user }}"

- name: Copy Gruvbox color scheme
  copy: src=files/gruvbox.vim dest={{ home_dir}}/.vim/colors/

- name: Copy Space Dark color scheme
  copy: src=files/space-dark.vim dest={{ home_dir}}/.vim/colors/

- name: Install Vim-plug
  get_url:
    url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    dest: "{{ ansible_env.HOME }}/.vim/autoload/plug.vim"
    mode: 0755
  become: yes
  become_user: "{{ user }}"

- name: Install Vim Plugins
  shell: vim +PlugInstall +qall

- name: Check FZF install
  stat: path={{ home_dir }}/.fzf
  register: fzf_installed

- name: Install FZF extensions
  shell: /usr/local/opt/fzf/install
  become: yes
  become_user: "{{ user }}"
  when: fzf_installed.stat.exists == False
